[package]
name = "platformer"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.15"

# Enable max optimizations for dependencies, but not my code, per Bevy's advice
[profile.dev.package."*"]
opt-level = 3